version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y nginx
  build:
    commands:
      - echo Build phase - copying files
      - cp index.html /var/www/html/index.html
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - index.html
    - appspec.yaml
    - scripts/install_nginx.sh
    - scripts/start_nginx.sh
